
filter:
  excluded_paths:
    - 'tests/*'

checks:
  php:
    return_doc_comments: true
    uppercase_constants: true
    no_goto: true
    optional_parameters_at_the_end: true
    parameters_in_camelcaps: true
    newline_at_end_of_file: true

tools:
  tools:
    php_cs_fixer:
      config: { level: psr2 }
